#!/usr/bin/env bash
set -ex

# Install and setup conda
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh Miniconda3-latest-Linux-x86_64.sh -b
rm -rf Miniconda3-latest-Linux-x86_64.sh
echo -e "\n"'export PATH=$PATH:/root/miniconda3/bin' >> /home/.bash_profile
export PATH=$PATH:/root/miniconda3/bin

# Update conda
conda update -n base -c defaults conda
conda config --set auto_activate_base false
conda init bash

# Install WhatsHap
conda install -y -c conda-forge mamba
mamba create -y -c conda-forge -c bioconda -n whatshap whatshap nomkl

# Add to PATH with conda activation
echo -e '\nconda activate whatshap' >> /home/.bash_profile # Set default conda environment
touch /usr/local/bin/whatshap
chmod 755 /usr/local/bin/whatshap
echo -e '#!/bin/bash\n\nsource /home/.bash_profile\n\nwhatshap $@\n' > /usr/local/bin/whatshap
